'use client';

interface DailyBriefingCardProps {
  briefing: string | null;
  loading: boolean;
  error: boolean;
  onRefresh: () => void;
}

export default function DailyBriefingCard({ briefing, loading, error, onRefresh }: DailyBriefingCardProps) {
  return (
    <div className="relative rounded-2xl overflow-hidden bg-gradient-to-br from-indigo-600 to-purple-700 p-6 text-white shadow-lg">
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xs font-semibold uppercase tracking-wider text-indigo-200">
              AI Morning Briefing
            </span>
            <span className="inline-flex items-center rounded-full bg-white/20 px-2 py-0.5 text-xs font-medium text-white">
              Generated by AI
            </span>
          </div>

          {loading && (
            <div className="space-y-2 animate-pulse">
              <div className="h-4 bg-white/30 rounded w-full" />
              <div className="h-4 bg-white/30 rounded w-5/6" />
              <div className="h-4 bg-white/30 rounded w-4/6" />
            </div>
          )}

          {!loading && error && (
            <p className="text-white/80 text-sm">
              Unable to generate briefing right now. Try refreshing in a moment.
            </p>
          )}

          {!loading && !error && briefing && (
            <p className="text-white text-base leading-relaxed">{briefing}</p>
          )}

          {!loading && !error && !briefing && (
            <p className="text-white/80 text-sm">
              Unable to generate briefing right now. Try refreshing in a moment.
            </p>
          )}
        </div>

        <button
          onClick={onRefresh}
          disabled={loading}
          className="flex-shrink-0 inline-flex items-center gap-1.5 rounded-lg bg-white/20 hover:bg-white/30 disabled:opacity-50 disabled:cursor-not-allowed px-3 py-2 text-sm font-medium text-white transition-colors"
          aria-label="Refresh briefing"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`}
          >
            <path
              fillRule="evenodd"
              d="M15.312 11.424a5.5 5.5 0 0 1-9.201 2.466l-.312-.311h2.433a.75.75 0 0 0 0-1.5H3.989a.75.75 0 0 0-.75.75v4.242a.75.75 0 0 0 1.5 0v-2.43l.31.31a7 7 0 0 0 11.712-3.138.75.75 0 0 0-1.46-.337Zm-2.068-6.873a.75.75 0 0 0-1.5 0v2.43l-.31-.31A7 7 0 0 0 1.72 9.809a.75.75 0 0 0 1.46.337 5.5 5.5 0 0 1 9.201-2.466l.312.311H10.26a.75.75 0 0 0 0 1.5h4.243a.75.75 0 0 0 .75-.75V4.499a.75.75 0 0 0-1.5 0v2.43l-.31-.31Z"
              clipRule="evenodd"
            />
          </svg>
          Refresh
        </button>
      </div>
    </div>
  );
}
